# Generated by Django 4.2.4 on 2023-08-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_book_options_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zip',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
