version: "3.10"

services:
  redis:
    container_name: redis_db
    image: redis:7.0-alpine
    restart: on-failure
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  shop_db:
    container_name: shop_db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - shop_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wrh_db:
    container_name: wrh_db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=db_wrh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - wrh_db:/var/lib/postgresql/data_wrh
    ports:
      - "5433:5432"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port

volumes:
  redis:
  shop_db:
  wrh_db: