version: "3.10"

services:
  redis:
    container_name: redis_db
    image: redis:7.0-alpine
    restart: on-failure
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  redis: